### PR TITLE
PMM-554: `pmm-admin add mongodb:queries`

### LINKED ISSUE #22: Proxying Consul to an External Consul Instance
We are running the pmm-server in Kubernetes. We already have instances of Prometheus, Grafana, and Consul running outside of the pmm-server. In the act of centralizing our monitoring and metrics, we have attempted to proxy the apps (specifically in this case, consul) to our external running consul app. We have done this successfully by altering the nginx configuration. However, the following line presents an issue, as our cluster leader is not running on localhost. 

https://github.com/percona/pmm-client/blob/master/pmm/main.go#L146

As expected, due to leader != "127.0.0.1:8300", our pmm client complains with the following error:

Unable to connect to PMM server by address: pmm.vividseats.test

Even though the server is reachable it does not look to be PMM server.
Check if the configured address is correct.

When we call <pmm-server-address>/v1/status/leader, we return a valid ip of our pmm server, "xxx.xx.xx.x:8300"

Could the code base be updated to not enforce this localhost constraint?

### PR DESCRIPTION
**Pull request by arvenil**
```terminal
$ pmm-admin add mongodb
[linux:metrics]   OK, now monitoring this system.
[mongodb:metrics] OK, now monitoring MongoDB metrics using URI localhost:27017
[mongodb:queries] OK, now monitoring MongoDB queries using URI localhost:27017
```

```terminal
$ pmm-admin add mongodb:queries
OK, now monitoring MongoDB queries using URI localhost:27017
```

Questions:

- [ ] Maybe we should warn user that he needs to enable profiling with `db.setProfilingLevel(2)` by himself?
- [x] Why we have condition leader != "127.0.0.1:8300" and not leader == ""? I wasn't able to mock consul with [httptest](https://golang.org/pkg/net/http/httptest/) because of this condition. This also would fix #22 - user wants to use external consul.
- [ ] Is this interface enough to monitor replicas/clusters?

### CODE REVIEW

File: pmm/main.go [hunk 1]
```diff
@@ -205,10 +205,25 @@ func (a *Admin) ServerInfo() {
...
+		"mysql:metrics",
+		"mysql:queries",
+		"mongodb:metrics",
+		"mongodb:queries",
+		"proxysql:metrics",
+	}
+	valid := false
+	for _, v := range svcTypes {
+		if v == svcType {
+			valid = true
```
Comment (percona-csalguero) [inline pmm/main.go]: Just a cosmetic change. You don't need the `valid` variable. You can just `return nil` if you find the element and avoid the `if` below

File: pmm/mongodb.go [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+// DetectMongoDB verify MongoDB connection.
+func (a *Admin) DetectMongoDB(uri string) (mgo.BuildInfo, error) {
+	dialInfo, err := mgo.ParseURL(uri)
+	if err != nil {
+		return mgo.BuildInfo{}, fmt.Errorf("Bad MongoDB uri %s: %s", uri, err)
+	}
+
+	dialInfo.Direct = true
+	dialInfo.Timeout = 10 * time.Second
+	session, err := mgo.DialWithInfo(dialInfo)
```
Comment (percona-csalguero) [inline pmm/mongodb.go]: Here you can use `pmgo` Dialer and you will have support for SSL

File: pmm/queries.go [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+
+// deleteInstance delete instance on QAN API.
+func (a *Admin) deleteInstance(uuid string) error {
+	// Remove MySQL instance from QAN.
+	url := a.qanAPI.URL(a.serverURL, qanAPIBasePath, "instances", uuid)
+	resp, content, err := a.qanAPI.Delete(url)
+	if err != nil {
+		return err
+	}
+	if resp.StatusCode != http.StatusNoContent {
```
Comment (percona-csalguero) [inline pmm/queries.go]: There is no STatusOK in the API?

File: pmm/queries.go [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+	if err != nil {
+		return "", err
+	}
+
+	config := &protocfg.Agent{}
+	if err := json.Unmarshal(jsonData, &config); err != nil {
+		return "", err
+	}
+
+	return config.UUID, nil
```
Comment (percona-csalguero) [inline pmm/queries.go]: What if the config is invalid and there is no UUID in the file?

File: pmm/queries.go [hunk 5]
```diff
@@ -0,0 +1,149 @@
...
+}
+
+// manageQAN enable/disable QAN on agent through QAN API.
+func (a *Admin) manageQAN(agentID, cmdName, UUID string, config map[string]interface{}) error {
+	var data []byte
+	if cmdName == "StartTool" {
+		data, _ = json.Marshal(config)
+	} else if cmdName == "StopTool" {
```
Comment (percona-csalguero) [inline pmm/queries.go]: I don't remember exactly but in some cases there is also a `RestartTool` command.

File: test/cmdtest/cmdtest.go [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+func (c *CmdTest) Write(data string) {
+	_, err := c.stdin.Write([]byte(data))
+	if err != nil {
+		panic(err)
+	}
+}
+
+func (c *CmdTest) Output() []string {
+	lines := []string{}
+OUTPUT_LINES:
```
Comment (percona-csalguero) [inline test/cmdtest/cmdtest.go]: just a cosmetic thing because lables remind me COBOL:
```
for {
		if line := c.ReadLine(); line != "" {
 			lines = append(lines, line)
                        continue
 		} 
}
```

File: pmm/main.go [hunk 7]
```diff
@@ -143,11 +143,11 @@ Use 'pmm-admin config' to define server user and password.`, a.Config.ServerAddr
 	}
 
 	// Check Consul status.
-	if leader, err := a.consulAPI.Status().Leader(); err != nil || leader != "127.0.0.1:8300" {
```
Comment (arvenil) [inline pmm/main.go]: Why we have this condition like `leader != "127.0.0.1:8300"` why not `leader == ""`? I wasn't able to mock consul with [httptest](https://golang.org/pkg/net/http/httptest/) because of this condition. This also would fix #22 - user wants to use external consul.

File: pmm/queries.go (hunk 3 above)
Comment (arvenil) [inline pmm/queries.go]: No. https://github.com/percona/qan-api/blob/b87e4cba8f8541ac112b23b628edd6fea29ac71e/app/controllers/instance.go#L161-L172
```go
// DELETE /instances/:uuid
func (c *Instance) Delete(uuid string) revel.Result {
	dbm := c.Args["dbm"].(db.Manager)
	if err := dbm.Open(); err != nil {
		return c.Error(err, "Instance.Delete: dbm.Open")
	}
	ih := instance.NewMySQLHandler(dbm)
	if err := ih.Delete(uuid); err != nil {
		return c.Error(err, "Instance.Delete: ih.Delete")
	}
	return c.RenderNoContent()
}
```

File: pmm/queries.go (hunk 5 above)
Comment (arvenil) [inline pmm/queries.go]: Yes, but `pmm-admin` doesn't use that

On installing service it sends cmd `StartTool` and on removing service it sends cmd `StopTool`.

To make this more clear and proper I've made changes:
* don't depend on string param that needs to be either StartTool or StopTool and if it's not StartTool or StopTool it brakes
* introduce `startQAN(agentID, qanConfig)` and `stopQAN(agentID, UUID)` that do what they say with different set of args; previously we had `manageQAN(agentID, "StartTool", "", qanConfig)` and `manageQAN(agentID, "StopTool", UUID, nil)` so you needed to know that with "StartTool" string you need to provide `qanConfig` but no `uuid` and reverse for "StopTool".

File: pmm/main.go (hunk 7 above)
Comment (arvenil) [inline pmm/main.go]: @rnovikovP @askomorokhov @percona-csalguero so you are fine with this change? It will also fix #22

Comment (roman-vynar) [inline pmm/main.go]: No particular reason, we just need to ensure there is a leader, otherwise consul is on elections :)  and don't accept requests.

Comment (arvenil) [inline pmm/main.go]: :) So `leader != ""` (for checking that there is a leader) should be enough, right?

Comment (roman-vynar) [inline pmm/main.go]: Correct, during election `/v1/status/leader` returns an empty string.

**Comment by arvenil** [comment]
PMM-910
